# Generated by Django 6.0.3 on 2026-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Other', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.URLField(max_length=1000)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('last_opened', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
